const animeSites = [
  {id:'onepiece', filter:'aventura', layout:'layout-map', name:'One Piece', title:'Grand Voyage', tag:'Mapa náutico', desc:'Site de aventura com mapa, ilhas, recompensas e chamada para tripulação.', colors:['#082f49','#0ea5e9','#facc15','#ffffff'], icon:'⚓'},
  {id:'kaiju', filter:'acao', layout:'layout-hud', name:'Kaiju No. 8', title:'Kaiju Defense', tag:'Alerta militar', desc:'Central tática com radar, ameaça, status de unidade e painel de evacuação.', colors:['#020617','#14532d','#ef4444','#ffffff'], icon:'⚠️'},
  {id:'bluelock', filter:'esporte', layout:'layout-arena', name:'Blue Lock', title:'Ego Striker', tag:'Arena competitiva', desc:'Página esportiva com placar, jogadores, rankings e cards de treinamento.', colors:['#020617','#1d4ed8','#38bdf8','#ffffff'], icon:'⚽'},
  {id:'jujutsu', filter:'acao', layout:'layout-domain', name:'Jujutsu Kaisen', title:'Cursed Domain', tag:'Energia amaldiçoada', desc:'Layout sombrio com domínio central, selos, energia e acesso secreto.', colors:['#080012','#4c1d95','#a78bfa','#ffffff'], icon:'⛩️'},
  {id:'fireforce', filter:'acao', layout:'layout-fire', name:'Fire Force', title:'Inferno Core', tag:'Fogo e brigada', desc:'Site quente com hero diagonal, chamadas de emergência e medidores de calor.', colors:['#120606','#dc2626','#fb923c','#ffffff'], icon:'🔥'},
  {id:'dandadan', filter:'cyber', layout:'layout-glitch', name:'Dandadan', title:'Paranormal Glitch', tag:'Neon caótico', desc:'Estrutura com cards desalinhados, investigação paranormal e visual glitch.', colors:['#080014','#c026d3','#06f7ff','#ffffff'], icon:'👁️'},
  {id:'frieren', filter:'magia', layout:'layout-rune', name:'Frieren', title:'Ancient Rune', tag:'Magia antiga', desc:'Página calma em formato grimório com capítulos, runas e formulário mágico.', colors:['#0f172a','#1e3a8a','#c4b5fd','#ffffff'], icon:'✦'},
  {id:'spyfamily', filter:'aventura', layout:'layout-mission', name:'Spy x Family', title:'Secret Mission', tag:'Arquivos secretos', desc:'Dashboard de missão com agentes, checklist, dossiê e área confidencial.', colors:['#111827','#166534','#f43f5e','#ffffff'], icon:'🕵️'},
  {id:'bleach', filter:'acao', layout:'layout-slash', name:'Bleach', title:'Soul Slash', tag:'Cortes espirituais', desc:'Layout com composição vertical, lâminas, clãs e medidor espiritual.', colors:['#030712','#111827','#38bdf8','#ffffff'], icon:'⚔️'},
  {id:'oshi', filter:'cyber', layout:'layout-stage', name:'Oshi no Ko', title:'Idol Stage', tag:'Palco neon', desc:'Site de idol com agenda, palco, ingressos, fã-clube e área de destaque.', colors:['#16051b','#db2777','#38bdf8','#ffffff'], icon:'⭐'}
];

const cssPath = 'anime-premium.css';
function styleVars(site){const [c0,c1,c2,fg]=site.colors;return `--c0:${c0};--c1:${c1};--c2:${c2};--fg:${fg};--icon:'${site.icon}'`;}
function nav(title){return `<nav class="preview-nav"><strong>${title}</strong><a href="#">Início</a><a href="#">Universo</a><a href="#">Personagens</a><button>Explorar</button></nav>`;}

function buildSite(site){
  const base = `anime-site-preview ${site.layout}`;
  const s = styleVars(site);
  if(site.layout==='layout-map') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="map-hero"><div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p><button>Entrar na tripulação</button></div><div class="treasure-map"><i>🏝️</i><i>☠️</i><i>⚓</i></div></div><div class="island-grid"><article>East Blue</article><article>Grand Line</article><article>New World</article><article>Recompensa</article></div><footer>Mapa interativo • ${site.name}</footer></section>`;
  if(site.layout==='layout-hud') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="hud-screen"><aside><b>DEFESA</b><span>Nível 08</span><span>Risco Alto</span><span>Unidade Ativa</span></aside><main><span>${site.tag}</span><h3>${site.title}</h3><div class="radar">${site.icon}</div><p>${site.desc}</p></main><aside><b>STATUS</b><div class="mini-bars"><i></i><i></i><i></i></div><button>Iniciar protocolo</button></aside></div><footer>Central de monitoramento • ${site.name}</footer></section>`;
  if(site.layout==='layout-arena') return `<section class="${base}" style="${s}">${nav(site.title)}<header class="scoreboard"><div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p></div><div class="score"><b>9</b><small>GOALS</small></div></header><div class="player-row"><article>Velocidade</article><article>Ego</article><article>Finalização</article></div><section class="training-card"><h4>Treino do dia</h4><button>Começar desafio</button></section></section>`;
  if(site.layout==='layout-domain') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="domain-core"><div class="seal">${site.icon}</div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p><button>Abrir domínio</button></div><div class="curse-panels"><article>Energia</article><article>Contrato</article><article>Barreira</article></div></section>`;
  if(site.layout==='layout-fire') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="fire-split"><div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p><button>Acionar brigada</button></div><div class="flame-card">${site.icon}</div></div><div class="heat-line"><i></i><i></i><i></i><i></i></div><footer>Temperatura crítica • ${site.name}</footer></section>`;
  if(site.layout==='layout-glitch') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="glitch-grid"><article class="big"><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p></article><article>${site.icon}<br>Fenômeno 01</article><article>Relatório paranormal</article><article><button>Investigar</button></article></div><footer>Arquivos instáveis • ${site.name}</footer></section>`;
  if(site.layout==='layout-rune') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="book"><section><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p></section><section class="runes"><b>✦</b><b>ᚱ</b><b>☾</b><button>Abrir grimório</button></section></div><div class="chapter-list"><article>Capítulo I</article><article>Capítulo II</article><article>Capítulo III</article></div></section>`;
  if(site.layout==='layout-mission') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="mission-board"><div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p></div><ul><li>✓ Identidade falsa</li><li>✓ Dossiê familiar</li><li>✓ Operação ativa</li></ul></div><div class="agent-cards"><article>Agente</article><article>Telepata</article><article>Alvo</article></div></section>`;
  if(site.layout==='layout-slash') return `<section class="${base}" style="${s}">${nav(site.title)}<div class="slash-layout"><aside>${site.icon}</aside><main><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p><button>Liberar energia</button></main></div><div class="spirit-meter"><i></i><i></i><i></i></div></section>`;
  return `<section class="${base}" style="${s}">${nav(site.title)}<div class="stage-hero"><div class="spotlight">${site.icon}</div><div><span>${site.tag}</span><h3>${site.title}</h3><p>${site.desc}</p><button>Entrar no fã-clube</button></div></div><div class="show-list"><article>Agenda</article><article>Ingressos</article><article>Backstage</article></div></section>`;
}

function buildStandalone(site){return `<!DOCTYPE html>\n<html lang="pt-br">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>${site.title}</title>\n<link rel="stylesheet" href="${cssPath}">\n</head>\n<body>\n${buildSite(site)}\n<script>\n${getSiteOnlyJs()}\n<\/script>\n</body>\n</html>`;}
function getSiteOnlyCss(){return Array.from(document.styleSheets).find(s=>s.href&&s.href.includes('anime-premium.css')) ? '/* Use o arquivo anime-premium.css enviado no ZIP. */' : '';}
function getSiteOnlyJs(){return `document.querySelectorAll('a[href="#"]').forEach(link=>link.addEventListener('click',event=>event.preventDefault()));`;}
async function loadCss(){try{return await (await fetch(cssPath)).text();}catch(e){return 'Abra com servidor local para copiar o CSS completo.';}}
async function copyText(text,button){try{await navigator.clipboard.writeText(text);}catch(e){const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();}const old=button.textContent;button.textContent='Copiado!';setTimeout(()=>button.textContent=old,1000);}
function renderSites(){const root=document.getElementById('animeSitesGrid');root.innerHTML=animeSites.map(site=>`<article class="anime-site-card" data-filter="${site.filter}" style="--c1:${site.colors[1]};--c2:${site.colors[2]}"><div class="kit-head"><div><span>${site.name}</span><h2>${site.title}</h2></div><em>${site.layout.replace('layout-','')}</em></div><p>${site.desc}</p><div class="site-preview-wrap">${buildSite(site)}</div><div class="copy-row"><button class="small-btn" data-copy="html" data-id="${site.id}">Copiar HTML</button><button class="small-btn" data-copy="css" data-id="${site.id}">Copiar CSS</button><button class="small-btn" data-copy="js" data-id="${site.id}">Copiar JS</button><button class="small-btn" data-copy="full" data-id="${site.id}">Copiar site completo</button></div></article>`).join('');}
function setupEvents(){document.addEventListener('click',async e=>{const copyBtn=e.target.closest('[data-copy]');if(copyBtn){const site=animeSites.find(item=>item.id===copyBtn.dataset.id);const type=copyBtn.dataset.copy;const content=type==='html'?buildSite(site):type==='css'?await loadCss():type==='js'?getSiteOnlyJs():buildStandalone(site);copyText(content,copyBtn);}const filterBtn=e.target.closest('.anime-site-filter');if(filterBtn){document.querySelectorAll('.anime-site-filter').forEach(btn=>btn.classList.remove('active'));filterBtn.classList.add('active');const filter=filterBtn.dataset.filter;document.querySelectorAll('.anime-site-card').forEach(card=>card.style.display=filter==='all'||card.dataset.filter===filter?'':'none');}if(e.target.matches('[data-copy-css]'))copyText(await loadCss(),e.target);});}
document.addEventListener('DOMContentLoaded',()=>{renderSites();setupEvents();});
